//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventario.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalidaProducto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SalidaProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime fechaField;
        
        private int cantidad_salidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int numSalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int cantidad_salida {
            get {
                return this.cantidad_salidaField;
            }
            set {
                if ((this.cantidad_salidaField.Equals(value) != true)) {
                    this.cantidad_salidaField = value;
                    this.RaisePropertyChanged("cantidad_salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int numSalida {
            get {
                return this.numSalidaField;
            }
            set {
                if ((this.numSalidaField.Equals(value) != true)) {
                    this.numSalidaField = value;
                    this.RaisePropertyChanged("numSalida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarService", ReplyAction="*")]
        AppInventario.ServiceReference.insertarServiceResponse insertarService(AppInventario.ServiceReference.insertarServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarService", ReplyAction="*")]
        System.Threading.Tasks.Task<AppInventario.ServiceReference.insertarServiceResponse> insertarServiceAsync(AppInventario.ServiceReference.insertarServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sku del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerStock", ReplyAction="*")]
        AppInventario.ServiceReference.traerStockResponse traerStock(AppInventario.ServiceReference.traerStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerStock", ReplyAction="*")]
        System.Threading.Tasks.Task<AppInventario.ServiceReference.traerStockResponse> traerStockAsync(AppInventario.ServiceReference.traerStockRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sku del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/serviceActualizaC", ReplyAction="*")]
        AppInventario.ServiceReference.serviceActualizaCResponse serviceActualizaC(AppInventario.ServiceReference.serviceActualizaCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/serviceActualizaC", ReplyAction="*")]
        System.Threading.Tasks.Task<AppInventario.ServiceReference.serviceActualizaCResponse> serviceActualizaCAsync(AppInventario.ServiceReference.serviceActualizaCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarService", Namespace="http://tempuri.org/", Order=0)]
        public AppInventario.ServiceReference.insertarServiceRequestBody Body;
        
        public insertarServiceRequest() {
        }
        
        public insertarServiceRequest(AppInventario.ServiceReference.insertarServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppInventario.ServiceReference.SalidaProducto sa;
        
        public insertarServiceRequestBody() {
        }
        
        public insertarServiceRequestBody(AppInventario.ServiceReference.SalidaProducto sa) {
            this.sa = sa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppInventario.ServiceReference.insertarServiceResponseBody Body;
        
        public insertarServiceResponse() {
        }
        
        public insertarServiceResponse(AppInventario.ServiceReference.insertarServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarServiceResult;
        
        public insertarServiceResponseBody() {
        }
        
        public insertarServiceResponseBody(bool insertarServiceResult) {
            this.insertarServiceResult = insertarServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class traerStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="traerStock", Namespace="http://tempuri.org/", Order=0)]
        public AppInventario.ServiceReference.traerStockRequestBody Body;
        
        public traerStockRequest() {
        }
        
        public traerStockRequest(AppInventario.ServiceReference.traerStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class traerStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sku;
        
        public traerStockRequestBody() {
        }
        
        public traerStockRequestBody(string sku) {
            this.sku = sku;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class traerStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="traerStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppInventario.ServiceReference.traerStockResponseBody Body;
        
        public traerStockResponse() {
        }
        
        public traerStockResponse(AppInventario.ServiceReference.traerStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class traerStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int traerStockResult;
        
        public traerStockResponseBody() {
        }
        
        public traerStockResponseBody(int traerStockResult) {
            this.traerStockResult = traerStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class serviceActualizaCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="serviceActualizaC", Namespace="http://tempuri.org/", Order=0)]
        public AppInventario.ServiceReference.serviceActualizaCRequestBody Body;
        
        public serviceActualizaCRequest() {
        }
        
        public serviceActualizaCRequest(AppInventario.ServiceReference.serviceActualizaCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class serviceActualizaCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sku;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cantidad;
        
        public serviceActualizaCRequestBody() {
        }
        
        public serviceActualizaCRequestBody(string sku, int cantidad) {
            this.sku = sku;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class serviceActualizaCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="serviceActualizaCResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppInventario.ServiceReference.serviceActualizaCResponseBody Body;
        
        public serviceActualizaCResponse() {
        }
        
        public serviceActualizaCResponse(AppInventario.ServiceReference.serviceActualizaCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class serviceActualizaCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int serviceActualizaCResult;
        
        public serviceActualizaCResponseBody() {
        }
        
        public serviceActualizaCResponseBody(int serviceActualizaCResult) {
            this.serviceActualizaCResult = serviceActualizaCResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : AppInventario.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AppInventario.ServiceReference.WebServiceSoap>, AppInventario.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppInventario.ServiceReference.insertarServiceResponse AppInventario.ServiceReference.WebServiceSoap.insertarService(AppInventario.ServiceReference.insertarServiceRequest request) {
            return base.Channel.insertarService(request);
        }
        
        public bool insertarService(AppInventario.ServiceReference.SalidaProducto sa) {
            AppInventario.ServiceReference.insertarServiceRequest inValue = new AppInventario.ServiceReference.insertarServiceRequest();
            inValue.Body = new AppInventario.ServiceReference.insertarServiceRequestBody();
            inValue.Body.sa = sa;
            AppInventario.ServiceReference.insertarServiceResponse retVal = ((AppInventario.ServiceReference.WebServiceSoap)(this)).insertarService(inValue);
            return retVal.Body.insertarServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppInventario.ServiceReference.insertarServiceResponse> AppInventario.ServiceReference.WebServiceSoap.insertarServiceAsync(AppInventario.ServiceReference.insertarServiceRequest request) {
            return base.Channel.insertarServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppInventario.ServiceReference.insertarServiceResponse> insertarServiceAsync(AppInventario.ServiceReference.SalidaProducto sa) {
            AppInventario.ServiceReference.insertarServiceRequest inValue = new AppInventario.ServiceReference.insertarServiceRequest();
            inValue.Body = new AppInventario.ServiceReference.insertarServiceRequestBody();
            inValue.Body.sa = sa;
            return ((AppInventario.ServiceReference.WebServiceSoap)(this)).insertarServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppInventario.ServiceReference.traerStockResponse AppInventario.ServiceReference.WebServiceSoap.traerStock(AppInventario.ServiceReference.traerStockRequest request) {
            return base.Channel.traerStock(request);
        }
        
        public int traerStock(string sku) {
            AppInventario.ServiceReference.traerStockRequest inValue = new AppInventario.ServiceReference.traerStockRequest();
            inValue.Body = new AppInventario.ServiceReference.traerStockRequestBody();
            inValue.Body.sku = sku;
            AppInventario.ServiceReference.traerStockResponse retVal = ((AppInventario.ServiceReference.WebServiceSoap)(this)).traerStock(inValue);
            return retVal.Body.traerStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppInventario.ServiceReference.traerStockResponse> AppInventario.ServiceReference.WebServiceSoap.traerStockAsync(AppInventario.ServiceReference.traerStockRequest request) {
            return base.Channel.traerStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppInventario.ServiceReference.traerStockResponse> traerStockAsync(string sku) {
            AppInventario.ServiceReference.traerStockRequest inValue = new AppInventario.ServiceReference.traerStockRequest();
            inValue.Body = new AppInventario.ServiceReference.traerStockRequestBody();
            inValue.Body.sku = sku;
            return ((AppInventario.ServiceReference.WebServiceSoap)(this)).traerStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppInventario.ServiceReference.serviceActualizaCResponse AppInventario.ServiceReference.WebServiceSoap.serviceActualizaC(AppInventario.ServiceReference.serviceActualizaCRequest request) {
            return base.Channel.serviceActualizaC(request);
        }
        
        public int serviceActualizaC(string sku, int cantidad) {
            AppInventario.ServiceReference.serviceActualizaCRequest inValue = new AppInventario.ServiceReference.serviceActualizaCRequest();
            inValue.Body = new AppInventario.ServiceReference.serviceActualizaCRequestBody();
            inValue.Body.sku = sku;
            inValue.Body.cantidad = cantidad;
            AppInventario.ServiceReference.serviceActualizaCResponse retVal = ((AppInventario.ServiceReference.WebServiceSoap)(this)).serviceActualizaC(inValue);
            return retVal.Body.serviceActualizaCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppInventario.ServiceReference.serviceActualizaCResponse> AppInventario.ServiceReference.WebServiceSoap.serviceActualizaCAsync(AppInventario.ServiceReference.serviceActualizaCRequest request) {
            return base.Channel.serviceActualizaCAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppInventario.ServiceReference.serviceActualizaCResponse> serviceActualizaCAsync(string sku, int cantidad) {
            AppInventario.ServiceReference.serviceActualizaCRequest inValue = new AppInventario.ServiceReference.serviceActualizaCRequest();
            inValue.Body = new AppInventario.ServiceReference.serviceActualizaCRequestBody();
            inValue.Body.sku = sku;
            inValue.Body.cantidad = cantidad;
            return ((AppInventario.ServiceReference.WebServiceSoap)(this)).serviceActualizaCAsync(inValue);
        }
    }
}
